[project]
name = "http-methods"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.12",
    "numpy>=2.2.5",
    "pandas>=2.2.3",
    "uvicorn>=0.34.2",
]
